server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location /api/ {
        client_max_body_size 2g;
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_request_buffering off;
        proxy_read_timeout 300s;
    }
    location /.well-known/ {
        proxy_pass http://backend:8000/.well-known/;
        proxy_set_header Host $host;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
